[paths]
data = /var/lib/grafana
logs = /var/log/grafana
plugins = /var/lib/grafana/plugins
provisioning = /etc/grafana/provisioning

[server]
protocol = http
http_addr = 0.0.0.0
http_port = 3000

[analytics]
reporting_enabled = false
check_for_updates = true

[security]
# Set initial administrator credentials outside Git.
disable_gravatar = true

[users]
allow_sign_up = false

[log]
mode = console file
level = info
